name: neural_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - pip
  - numpy
  - libblas=*=*openblas
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - scikit-image
  - pytorch=2.3.0=cpu_py39*
  - jupyter
  - notebook
  - ipykernel
  - ipython
  - ipywidgets
  - h5py
  - numba
  - imageio
  - pillow
  - tqdm
  - pyyaml
  - pyzmq
  - pywavelets
  - anyio
  - argon2-cffi
  - async-lru
  - attrs
  - beautifulsoup4
  - bleach
  - cffi
  - colorama
  - contourpy
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - exceptiongroup
  - executing
  - fonttools
  - fsspec
  - h5py
  - hdf5
  - importlib-metadata
  - jinja2
  - jsonschema
  - jupyterlab
  - kiwisolver
  - markupsafe
  - packaging
  - platformdirs
  - prompt-toolkit
  - psutil
  - pygments
  - pyparsing
  - python-dateutil
  - requests
  - setuptools
  - six
  - tornado
  - traitlets
  - typing-extensions
  - zipp
  - ipympl
